root = "." 
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main main.go"
bin = "tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl"]
exclude_dir = ["public", "tmp", "READM.md"]
exclude_regex = ["_test\\.go"]
delay = 0
stop_on_error = true
log = "air_errors.log"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true